name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  CI:
    runs-on: ubuntu-latest
    concurrency:
      group: CI
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "Install Nix"
      uses: cachix/install-nix-action@v18
      with:
        install_url: https://releases.nixos.org/nix/nix-2.13.3/install
    - name: "Set Up Binary Cache"
      if: github.event_name != 'pull_request'
      uses: cachix/cachix-action@v12
      with:
        name: t2linux
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        pushFilter: "(squashfs.img$|x86_64-linux.iso$)"
    - name: Build
      env:
        GC_DONT_GC: 1
      run: |
        function printstuff() {
            while true
            do
                sudo df -h
                sudo findmnt
                sleep 10
            done
        }

        printstuff &

        sudo mount -o remount,size=30G /run/user/1001

        for iso in $(nix flake show --json | nix run nixpkgs#jq -- -r keys[]); do
          nix build .#$iso
          split -d result/iso/*.iso -b 1G $iso.iso-part-
          rm result
        done
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')
      with:
        files: "*.iso-part-*"
